version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    restart: always
    ports:
      - "1883:1883"
    expose:
      - "1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config
  #hv:
  #  image: ghcr.io/janjantestorgan/tracker_dcs_dummy:main
  #  restart: always
  #  links:
  #    - mosquitto  
  #  command: ['python', 'dummy/hv.py', 'hv', 'mosquitto']
volumes:
  mosquitto_data:
  mosquitto_log:

