name: Docker-Image-Build-Publish
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME_DUMMY: tracker_dcs_dummy
  IMAGE_NAME_LOW_VOLTAGE: low_voltage

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        -
          name: Checkout 
          uses: actions/checkout@v2
        -
          name: Docker metadata
          id: meta
          uses: docker/metadata-action@v3
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            tags: |
              type=ref,event=branch
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
        -
          name: Login to ghcr
          uses: docker/login-action@v1
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
       
        -
          name: pull dummy low_voltage image
          run: |
            
            docker pull ghcr.io/janjantestorgan/tracker_dcs_dummy:main
            docker pull {{env.REGISTRY }}/${{github.actor}}/${{env.IMAGE_NAME_DUMMY}}
            docker pull ghcr.io/janjantestorgan/low_voltage:main
            docker pull {{env.REGISTRY }}/${{github.actor}}/${{env.IMAGE_NAME_LOW_VOLTAGE}}
            docker images
      #  -
      #    name: Set up Docker Buildx
      #    uses: docker/setup-buildx-action@v1
      #    uses: docker/build-push-action@v2
      #    with:
      #      context: .
      #      file: ./Dockerfile
      #      push: true
      #      tags: ${{ steps.meta.outputs.tags }}
      #      labels: ${{ steps.meta.outputs.labels }}    
       